last_change = 2026-09-11T03:33:55.364933Z
addr = 0xf25f90
size = 0xc1
name = "IGameSystem_LoopPreShutdownAllSystems"

[header]
name = "IGameSystem_LoopPreShutdownAllSystems"
addr = 0xf25f90

[header.args]
