last_change = 2026-09-11T03:33:55.364982Z
addr = 0x16148c0
size = 0xfd
name = "CBasePlayerController_CheckForLocalPlayer"

[header]
name = "CBasePlayerController_CheckForLocalPlayer"
addr = 0x16148c0

[header.args]
