last_change = 2026-09-10T06:54:32.837499Z
addr = 0x1699fc0
size = 0x64
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_CreateGameSystem"

[header]
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_CreateGameSystem"
addr = 0x1699fc0

[header.args]
