last_change = 2026-09-11T03:33:55.365018Z
addr = 0x16fe7e0
size = 0x2c4
name = "CNetworkGameClient_OnSource1Source1LegacyGameEvent"

[header]
name = "CNetworkGameClient_OnSource1Source1LegacyGameEvent"
addr = 0x16fe7e0

[header.args]
