last_change = 2026-09-10T18:37:41.695186Z
addr = 0x17273f0
size = 0xf
name = "CLoopModeGame_OnClientPostOutput"
type = "void"

[header]
name = "CLoopModeGame_OnClientPostOutput"
addr = 0x17273f0
type = "void"

[header.args]
