last_change = 2026-09-11T03:33:55.365059Z
addr = 0x1726ed0
size = 0xbb
name = "CLoopModeGame_OnClientAdvanceNonRenderedFrame"

[header]
name = "CLoopModeGame_OnClientAdvanceNonRenderedFrame"
addr = 0x1726ed0

[header.args]
