last_change = 2026-09-11T03:33:55.365131Z
addr = 0x172ef20
size = 0x1d8
name = "CLoopModeFactory_CLoopModeGame_Shutdown"

[header]
name = "CLoopModeFactory_CLoopModeGame_Shutdown"
addr = 0x172ef20

[header.args]
