last_change = 2026-09-11T03:33:55.365048Z
addr = 0x1726d50
size = 0xbb
name = "CLoopModeGame_OnClientPollNetworking"

[header]
name = "CLoopModeGame_OnClientPollNetworking"
addr = 0x1726d50

[header.args]
