last_change = 2026-09-11T03:33:55.365085Z
addr = 0x17272c0
size = 0xf3
name = "CLoopModeGame_OnClientPostSimulate"

[header]
name = "CLoopModeGame_OnClientPostSimulate"
addr = 0x17272c0

[header.args]
