last_change = 2026-09-10T18:37:41.695236Z
addr = 0x1743f40
size = 0xe84
name = "CLoopModeGame_LoopInit"
type = "long long"

[header]
name = "CLoopModeGame_LoopInit"
addr = 0x1743f40
type = "long long"

[header.args]
