last_change = 2026-09-10T18:37:41.695295Z
addr = 0x18bdd60
size = 0x12b
name = "CSource2Client_OnDisconnect"
type = "long long"

[header]
name = "CSource2Client_OnDisconnect"
addr = 0x18bdd60
type = "long long"

[header.args]
